use_frameworks!

platform :ios, '8.0'

target 'Alib_Example' do
  pod 'Alib', :path => '../'

  target 'Alib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
